### ISSUE TITLE
[BUG] Wiki

### ISSUE THREAD

**Issue by Tazler89** [Darkw1nged/Peligon-Plugins#15]
your wiki don't work keep getting You do not have permission to update this wiki.

**Comment by Darkw1nged** [comment]
Hello, 
Sorry about this. As of the last couple of days I have been working on updating the github page. Can you please tell me what you were wanting to look at and i will make it up first?

Thanks.

**Comment by Tazler89** [comment]
i was just wanting to know about the plugin, i am looking for a plugin that i cannot seem to find, and its just becoming a pain, every plugin i have found is no longer updated, i did test yours a little bit and it had errors flagging up when trying to do balance, and don't think it done as i needed, if you need tester or someone to help with ideas for you plugin i would be happy to help i have many ideas, but you would need to have lots of time to do coding lol, i support a few devs and have helped improve many plugins over the years, i also help build wikies and supply discord support for a few also.

**Comment by Darkw1nged** [comment]
Hello,
Im assuming you are talking about the Economy plugin?
Can you please tell me what errors you are experiencing and also tell me any ideas you would like to see in the plugin and i will add them to the todo list!
Thanks!

**Comment by Tazler89** [comment]
do you have discord or something as think is abit to long for here

**Comment by Darkw1nged** [comment]
Sure, You can add me on discord. darkwinged#7539
