### ISSUE TITLE
question

### ISSUE THREAD

**Issue by Zarkness** [Darkw1nged/Peligon-Plugins#6]
Hi, I was wondering if you had a discord group for support etc...

and i would also like to suggest for the skyblock dangeron that you add a multi island system and also add support for the slimeworldmanager.

**Comment by Darkw1nged** [comment]
Hello,
As of right now there is no support discord and you can post your bug reports and questions here.
Can you please tell me mote about what plugin this should be added to and go more in depth about your request?

Cheers, darkwinged.

**Comment by Zarkness** [comment]
Okay, thank you very much.

my request/suggestion is for the plugin peligon-Skyblock.
and what I suggest is to add support for the plugin slimeworldmanager and add a system of multiple islands, ie the user can create different islands as in hypixel skyblock, a way to choose the island you want to go could be with /is select <id island> and select your island with that id and then when you put /is go or any command relating to the island will be to that island, the idea is more or less the system that has hypixel skyblock that each island is as if you started from scratch but without losing the previous island

**Comment by Darkw1nged** [comment]
Hello, Thank you for your suggestion.
As of right now Skyblock is not in full development phase and im currently working on some other things with Peligon.
I will keep these features in mind however and i do not want to completely copy hypixel.
Peligon Skyblock may take some time to develop as it is not a priority as of the moment.

Cheers, darkwinged.

**Comment by Zarkness** [comment]
ok and thank you very much, the system does not have to be the same I can make my users have multiple islands and then already with a menu through a plugin menus and I will do the menu and everything else, it is not necessary to copy the full hypixel, I just said it so you understand something me
