### ISSUE TITLE
[Feature Request] Pause Playtime with a command

### ISSUE THREAD

**Issue by GreenArrowlol** [Darkw1nged/Peligon-Plugins#7]
**A description of a feature you want.**
feature to pause the playtime with a command would be useful for staff use.
there might be a time when they have to toggle maintenance and if the admins needed staff members like mods or helpers they'd have extra playtime as they'd be spending a lot of time during the maintenance. Kinda a disadvantage so it'd be better to be able to pause the playtime for players.
**Additional context**

**Comment by Darkw1nged** [comment]
@GreenArrowlol Just to let you know the resource has now been updated and includes your feature request.
Link: [https://www.spigotmc.org/resources/peligon-playtime.101707/](url)

**Comment by GreenArrowlol** [comment]
Cool
